[build-system]
requires = ["scikit-build-core", "cython", "cython-cmake", "numpy", "mpi4py"]
build-backend = "scikit_build_core.build"

[project]
version = "0.0.1"
name = "parrsb"
description = ""
license = "MIT"
readme = "README.md"
authors = [
    { name = "Thilina Ratnayaka", email = "thilinarmtb@gmail.com" },
]
requires-python = ">=3.10"
dependencies = [
    "mpi4py>=4.1.1",
    "numpy>=2.2.6",
]

[dependency-groups]
dev = [
  "pytest>=8.0",
  "cython-lint",
  "isort>=8",
]

[tool.cython-lint]
max-line-length = 88

[tool.isort]
profile = "black"
line_length = 88
