name: CI tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with tmate (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.debug_enabled }}
      - name: Install apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y openmpi-bin libopenmpi-dev
          sudo apt install -y cmake
      - name: Run unit tests
        shell: bash
        run: |
          CC=mpicc MPIOPTS="--oversubscribe" ./bin/test.sh
      - name: Block to allow inspecting failures
        run: sleep 60m
        if: ${{ failure() && inputs.debug_enabled }}
