name: Linting checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with tmate (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
env:
  VENV: ${{ github.workspace }}/.venv
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.debug_enabled }}
      - name: Initialize the venv
        shell: bash
        run: |
          VIRTUAL_ENV=${VENV} uv sync --active --no-install-project
      - name: Run cython-lint in src/
        shell: bash
        run: |
          source ${VENV}/bin/activate
          cython-lint src/
      - name: Run isort in src/
        shell: bash
        run: |
          source ${VENV}/bin/activate
          isort src/
    - name: Run ruff format in tests/
      uses: astral-sh/ruff-action@v3
      with:
        src: "./tests"
        args: "format --check --diff"
      - name: Block to allow inspecting failures
        run: sleep 60m
        if: ${{ failure() && inputs.debug_enabled }}
